- lib/microformats/derive-slug.js
- lib/microformats/form-encoded-to-mf2.js
- lib/templates/article.njk
- lib/templates/audio.njk
- lib/templates/bookmark.njk
- lib/templates/checkin.njk
- lib/templates/event.njk
- lib/templates/like.njk
- lib/templates/note.njk
- lib/templates/photo.njk
- lib/templates/reply.njk
- lib/templates/repost.njk
- lib/templates/video.njk
- test/app/middleware/admin.test.js
- test/lib/microformats/fixtures/slug-provided-empty.json
- test/lib/microformats/fixtures/slug-provided.json
- test/lib/microformats/form-encoded-to-mf2.test.js
* Moves all extended micropub properties (`mp-`) into `mf2.properties` and strips `mp-` from their names, i.e. `mf2['mp-slug']` → `mf2.propertries.slug`, `mf2['mp-syndicate-to']` → `mf2.propertries['syndicate-to]`, etc.
* Updates `derviveSlug` function given the above change
* Adds support for `mp-syndicate-to` property to default post templates. If present, a YAML array is created under the `syndicate-to` key:
```
syndicate-to:
- https://twitter.com/username
- https://micro.blog/username
```
Fixes #38.
> Add support for `mp-syndicate-to` property

- README.md
- packages/endpoint-media/lib/media.js
- packages/endpoint-media/tests/helpers/publication.js
- packages/endpoint-media/tests/lib/media.js
- packages/endpoint-micropub/lib/post.js
- packages/endpoint-micropub/tests/helpers/publication.js
- packages/endpoint-micropub/tests/lib/post.js
- packages/indiekit/config/defaults.js
- packages/store-github/README.md
- packages/store-github/index.js
- packages/store-github/tests/index.js
- packages/store-gitlab/README.md
- packages/store-gitlab/index.js
- packages/store-gitlab/tests/index.js
While this doesn’t entirely address #63, it makes localising commit messages possible, should you ever want to.
> feat: customise commit message format. fixes #63

- packages/preset-hugo/index.js
- packages/preset-hugo/package.json
- packages/preset-hugo/tests/unit/preset.js
[Go templates don’t accept hyphens in property names](https://github.com/gohugoio/hugo/issues/1474), and [Hugo camelCases its predefined front matter keys](https://gohugo.io/content-management/front-matter/).
This PR ensures all front matter (including nested ones) use camelCased key names. Fixes #345.
> Use camelcased frontmatter keys

- packages/store-gitea/README.md
Fix the name of the var host to instance. Took me a long time to figure it out on my install.
> Fix store-gitea README typo

- package-lock.json
- package.json
- packages/store-ftp/README.md
- packages/store-ftp/index.js
- packages/store-ftp/package.json
Adds support for FTP as a content store. It’s missing tests, but wasn’t able to work out how to stub out a fake FTP server to test against.
This plug-in really exists to demonstrate the ability to connect to content stores that are not Git repositories, so it’s worth publishing for that reason alone.
> Add FTP content store plug-in. Fixes #278

- docs/customisation/post-types.md
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/post-type-count.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/tests/unit/utils.js
Per discussion here: https://github.com/getindiekit/indiekit/issues/257
This does nothing more than create a `post` url token to search the MongoDB (if it exists and is called) for the count of posts (of a given type) created in the day. No new database creations.
If the `n` token is used, but no database connection is configured, it will throw an error.
> feat(n token): add post type count token for the day

- docs/plug-ins.md
- package-lock.json
- package.json
- packages/store-file-system/README.md
- packages/store-file-system/assets/icon.svg
- packages/store-file-system/index.js
- packages/store-file-system/package.json
- packages/store-file-system/tests/unit/store.js
Useful for testing Indiekit locally. Fixes #420.
Only tested on macOS, though uses Node.js `fs` module so _should_ work across different environments. Can address any issues as/when they arise.
Thanks to @aciccarello for idea and an initial implementation.
> Add file system store

- helpers/config/index.js
- packages/indiekit/lib/publication.js
- packages/indiekit/tests/unit/publication.js
Previously, custom post types would only be used if a preset was being used also. However, a preset is optional, so not having a preset shouldn’t stop other values being set.
> Return custom post types if no preset provided

- docs/options.md
- helpers/mock-agent/website.js
- packages/endpoint-micropub/lib/controllers/action.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/post.js
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/preset-hugo/index.js
- packages/preset-jekyll/index.js
Disabled by default, this PR adds a new option `publication.enrichPostData`. If enabled, Indiekit will try to fetch Microformats data for any URL given in a new post (for example URLs for `bookmark-of`, `like-of`, `repost-of`, `in-reply-to`).
This has been sitting around in a branch since the discussion first arose in #147. In retrospect, it’s a perfectly fine advanced feature to include (although certainly not something to enable by default). Anyway, with the benefit of time and given subsequent refactors that have happened around post data in the interim, happy with how this is now incorporated into the overall flow of things.
Have tried to document this feature as best as possible, but like all things IndieWeb, it’s complicated 😒
> Enrich post data with Microformats from referenced URLs

- README.md
- docs/.vitepress/config.js
- docs/configuration/post-types.md
- package-lock.json
- package.json
- packages/endpoint-micropub/lib/post-type-count.js
Indiekit currently throws an error when attempting to create a post if no database has been configured (see: #502). Yet the documentation says a database is optional.
Resolve this ambiguity by:
* Not throwing an error, but instead logging a warning to the console
* Adding a footnote to [list of tokens](https://getindiekit.com/configuration/post-types#path-and-url-tokens) that `n` requires a database configured.
* The above requiring adding `markdown-it-footnote` support to VitePress
* Add a note to the requirements section in the README
> Warn about database requirement when attempting to get post count

- README.md
Found your sample configuration very handy, thanks for this. With the move to v1.x, it seems your config file went from `index.js` to `indiekit.config.cjs`.
> docs: fix README link to example server configuration

- docs/configuration/index.md
- helpers/config/index.js
- packages/endpoint-auth/index.js
- packages/endpoint-auth/lib/controllers/metadata.js
- packages/endpoint-auth/views/auth.njk
- packages/endpoint-files/lib/controllers/file.js
- packages/endpoint-files/lib/controllers/files.js
- packages/endpoint-files/lib/controllers/upload.js
- packages/endpoint-media/index.js
- packages/endpoint-micropub/index.js
- packages/endpoint-micropub/lib/config.js
- packages/endpoint-micropub/lib/controllers/action.js
- packages/endpoint-micropub/lib/media.js
- packages/endpoint-micropub/tests/integration/404-query-source-url-not-found.js
- packages/endpoint-micropub/tests/unit/media.js
- packages/endpoint-posts/lib/controllers/post.js
- packages/endpoint-posts/lib/controllers/posts.js
- packages/endpoint-share/lib/controllers/share.js
- packages/endpoint-syndicate/lib/controllers/syndicate.js
- packages/endpoint-syndicate/tests/unit/utils.js
- packages/indiekit/lib/endpoints.js
- packages/indiekit/lib/indieauth.js
- packages/indiekit/lib/middleware/locals.js
- packages/indiekit/locales/en.json
- packages/indiekit/tests/integration/200-session-auth.js
- packages/indiekit/tests/integration/401-session-auth-invalid-token.js
- packages/indiekit/tests/unit/endpoints.js
- packages/indiekit/tests/unit/indieauth.js
- packages/indiekit/views/status.njk
Fixes #507. Am using a private variable in the default endpoint plugins, but I think this is fine. Default endpoints can either be overwritten by a user’s config (documentation updated), or by a subsequent plugin providing a fully resolved URL for these values (I think… not tested, but not important right now).
> Refactor application endpoints

- packages/endpoint-posts/index.js
- packages/endpoint-posts/lib/controllers/delete.js
- packages/endpoint-posts/lib/controllers/post.js
- packages/endpoint-posts/lib/controllers/posts.js
- packages/endpoint-posts/lib/utils.js
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/tests/integration/200-get-delete.js
- packages/endpoint-posts/tests/integration/302-get-delete.js
- packages/endpoint-posts/tests/integration/302-post-delete.js
- packages/endpoint-posts/tests/integration/400-post-delete.js
- packages/endpoint-posts/tests/unit/utils.js
- packages/endpoint-posts/views/delete-post.njk
- packages/endpoint-posts/views/post.njk
- packages/frontend/components/file-list/styles.css
- packages/frontend/components/file-list/template.njk
Following on from #514, this PR implements the same action but for deleting posts.
Deleting posts is a bit different as, while they do get deleted in the content store, the post remains in the database so that it can be undeleted in the future. It also remains queryable via Micropub, with it’s `post-status` updated to `deleted` (see 6350d7faebb9a1b50e01a9e3cb9f26e619f0b465).
I’ve added an initial deleted file style, but more work needs to be done on the design of this component:
> Delete a post

- packages/endpoint-json-feed/includes/endpoint-json-feed-widget.njk
- packages/endpoint-posts/includes/endpoint-posts-widget.njk
- packages/endpoint-posts/index.js
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/package.json
- packages/endpoint-share/assets/icon.svg
- packages/endpoint-share/includes/endpoint-share-widget.njk
- packages/endpoint-share/index.js
- packages/endpoint-share/package.json
- packages/frontend/components/bookmarklet/styles.css
- packages/frontend/components/button/styles.css
- packages/frontend/components/button/template.njk
- packages/frontend/components/fieldset/styles.css
- packages/frontend/components/fieldset/template.njk
- packages/frontend/components/widget/macro.njk
- packages/frontend/components/widget/styles.css
- packages/frontend/components/widget/template.njk
- packages/frontend/layouts/default.njk
- packages/indiekit/views/homepage.njk
- packages/preset-hugo/index.js
- packages/preset-jekyll/index.js
I couldn’t help myself… There was already a sorta-widget system on the status page, but it wasn’t really that obvious or useful. Now that we’ve finally created a homepage, separate from the status page (f4782db19ef1245ca4c1f7f879783482e2b27f80), can go to town a bit here.
3 plug-ins with widgets so far:
* Share bookmarklet
* JSON Feed
* Posts – links to create different posts types, which is cart-before-horse stuff as that functionality doesn’t exist yet :blush:
> Homepage widgets

- packages/endpoint-micropub/lib/controllers/query.js
- packages/endpoint-micropub/lib/mf2.js
- packages/endpoint-micropub/tests/integration/200-query-source-url-property.js
- packages/endpoint-micropub/tests/integration/200-query-source.js
- packages/endpoint-posts/lib/utils.js
Tripped over during the difficult dance between JF2 and mf2. Fixed so that:
* `q=source` returns an `items` `Array`
* `q=source&url=*` returns an mf2 `object`
Added tests and made existing ones a bit stricter.
(See https://github.com/barryf/micropublish/issues/111#issuecomment-1345506312)
> Correct Micropub source URL query

- helpers/post-data/index.js
- packages/endpoint-micropub/lib/controllers/action.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/post.js
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/endpoint-micropub/tests/unit/post.js
- packages/endpoint-posts/lib/controllers/post.js
- packages/endpoint-posts/lib/controllers/posts.js
- packages/endpoint-posts/views/post.njk
- packages/frontend/components/file-list/template.njk
- packages/preset-hugo/index.js
- packages/preset-hugo/tests/index.js
- packages/preset-jekyll/index.js
- packages/preset-jekyll/tests/index.js
Changes behaviour such that:
* Deleting posts no longer delete files (more of a soft delete… or soft*er* delete). 
Now properties are deleted (except for those used in permalink creation) and a `deleted` date time is added. This means it’s possible to keep pages on a publication with a `401 Gone` status, and possibly a message about the page having been deleted, rather than respond with `404 Not Found` (See *[deleted](https://indieweb.org/deleted)* on the IndieWeb wiki).
* Deleted properties are now storied in a private `_deletedProperties` object, meaning deleted properties are no longer exposed when querying the Micropub endpoint
> Refactor Micropub delete/undelete behaviour

- packages/indiekit/config/defaults.js
Fixes getindiekit/indiekit#556
It doesn't appear that there are currently any tests for **config/defaults.js** or **lib/config.js**, so I've not written a regression test for this. Let me know if you need me to add one.
I was unable to test this fix locally due to #558, but it looks straightforward. 🤞🏻
> fix: use MONGO_URL env variable if specified

- docs/get-started.md
The indiekit binary will not be on the path in most server environments. The simplest way to run this reliably in most places is to use npx.
> docs: use npx to run indiekit serve

- helpers/fixtures/jf2/article-content-provided-html-text.jf2
- helpers/fixtures/jf2/article-content-provided-text.jf2
- helpers/fixtures/jf2/article-content-provided.jf2
- helpers/fixtures/jf2/note-content-provided-html-text-mixed.jf2
- helpers/fixtures/jf2/note-content-provided-html-text.jf2
- helpers/fixtures/jf2/note-content-provided-html-with-link.jf2
- helpers/fixtures/jf2/note-content-provided-html.jf2
- package-lock.json
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/markdown.js
- packages/endpoint-micropub/package.json
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/endpoint-micropub/tests/unit/markdown.js
- packages/syndicator-mastodon/tests/unit/utils.js
- packages/syndicator-twitter/tests/unit/utils.js
Not sure why I was using `striptags` when I already had the `htmlToMarkdown` function (that uses Turndown) that achieves roughly similar. Maybe it’s because of the issues I encountered trying to use it this time round:
1. encoding Markdown as Markdown with Turndown leads to escaping of markdown characters:
```md
This is a [link](/)
```
becomes
```md
This is a \\[link\\](/)
```
2. encoding Markdown as Markdown means any existing line breaks are ignored:
```md
Paragraph
> Blockquote
```
becomes
```md
Paragraph > Blockquote
```
However, we can avoid these issues by
1. [Disabling the escaping of Markdown characters in Turndown](https://github.com/mixmark-io/turndown#escaping-markdown-characters)
2. Converting Markdown to HTML before converting it back to Markdown
…and that means we can remove …
> Correctly encode html/text content containing `<`/`>` characters

- helpers/fixtures/jf2/article-content-provided-as-html.jf2
- helpers/fixtures/jf2/article-content-provided-as-text.jf2
- helpers/fixtures/jf2/article-content-provided-html-text-mixed.jf2
- helpers/fixtures/jf2/article-content-provided-text.jf2
- helpers/fixtures/jf2/article-content-provided.jf2
- helpers/fixtures/jf2/note-content-provided-html-text-mixed.jf2
- helpers/fixtures/jf2/note-content-provided-html-text.jf2
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/markdown.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/endpoint-micropub/tests/unit/markdown.js
- packages/endpoint-micropub/tests/unit/utils.js
Content can arrive in many forms. Ideally it would arrived as an object with `content.html` and `content.text` representations. Sometimes, only one of these values will be provided, or a string is provided in `content`, which could be either text or HTML.
Indiekit aims attempts to normalise any incoming content request, and generate text and HTML representations:
* Text can be derived from HTML, using Turndown.
* HTML can be derived from text, using markdown-it.
As part of this normalisation, any value for `context.text` (or a `content` string), was parsed as HTML and converted back to Markdown. This change was made in #564 (we needed to parse markdown as HTML and back into Markdown to prevent issues with line breaks). But boy oh boy, this was real funky. 🕺
However, as @sentience [pointed …
> `content.text` improvements

- packages/endpoint-syndicate/lib/controllers/syndicate.js
- packages/endpoint-syndicate/lib/utils.js
- packages/endpoint-syndicate/tests/unit/utils.js
(Waiting for test environment to pick up this branch so I can test if this fixes things)
Prevent repeated syndications by:
* Only syndicating if the target hasn’t already been syndicated to
* Abstracting parts of the syndication logic into smaller helpers that can be unit tested
There might still be issues, next thing to investigate is the Micropub update query…
Fixes #569
> Prevent repeated syndication

- packages/syndicator-mastodon/README.md
- packages/syndicator-mastodon/index.js
- packages/syndicator-mastodon/lib/mastodon.js
- packages/syndicator-mastodon/lib/utils.js
- packages/syndicator-mastodon/tests/unit/mastodon.js
- packages/syndicator-mastodon/tests/unit/utils.js
This PR adds a `characterLimit` option to the Mastodon syndicator, defaulting to `500`.
Also:
* Renames a `url` variable to be consistent with the use of `serverUrl` throughout other parts of the plug-in
* Refactors `createStatus()` to pass properties and an options object (looks like incorrect values were passed to this method for reposts)
Fixes #572.
> Add option for character limit to Mastodon syndicator

- helpers/fixtures/jf2/article-content-provided-as-html.jf2
- helpers/fixtures/jf2/article-content-provided-as-text.jf2
- helpers/fixtures/jf2/article-content-provided-html-text-mixed.jf2
- helpers/fixtures/jf2/article-content-provided-html-text.jf2
- helpers/fixtures/jf2/article-content-provided-html.jf2
- helpers/fixtures/jf2/article-content-provided-text.jf2
- helpers/fixtures/jf2/article-content-provided.jf2
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/markdown.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/endpoint-micropub/tests/unit/utils.js
Previously, this endpoint accounted for the following cases for an incoming JF2 `content` property: 
* HTML being provided for `content.text`
* HTML being provided for `content`
This may be a case of over engineering:
1. If plaintext contains HTML, this should be considered intentional. Markdown can include inline HTML elements which don’t have equivalents in Markdown (i.e. `<cite>`).
2. If plaintext is entirely HTML, that’s an issue with the Micropub client: it should send content using the correct Microformats representation (which is also `content.html`), and therefore an issue should be filled against that client.
This PR:
* removes any attempt to detect HTML in plaintext and convert it to Markdown
* adds missing test for deriving `content.text` from sole `content.html` value
* adds …
> Micropub endpoint: Try to be less clever deriving `text` and `html` JF2 values

- docs/introduction.md
- packages/preset-hugo/index.js
- packages/preset-hugo/tests/index.js
- packages/preset-jekyll/index.js
- packages/preset-jekyll/tests/index.js
Like `mp-slug` and `mp-photo-alt`, incoming properties prefixed with `mp-*` are directives for the server, and shouldn’t be published.
This PR prevents `mp-syndicate-to` being included in published post files, and updates the documentation that previously included an example of this value being shown in post files.
> Don’t include `mp-syndicate-to` in post file

- helpers/frontend/views/frontend-components.njk
- packages/endpoint-auth/lib/controllers/documentation.js
- packages/endpoint-files/lib/controllers/delete.js
- packages/endpoint-files/lib/controllers/form.js
- packages/endpoint-posts/lib/controllers/delete.js
- packages/endpoint-posts/lib/controllers/form.js
- packages/endpoint-posts/tests/integration/500-post-create.js
- packages/endpoint-share/lib/controllers/share.js
- packages/endpoint-share/tests/integration/400-post-share.js
- packages/frontend/components/authorize/template.njk
- packages/frontend/components/details/styles.css
- packages/frontend/components/details/template.njk
- packages/frontend/components/notification/styles.css
- packages/frontend/components/notification/template.njk
- packages/frontend/layouts/default.njk
- packages/indiekit/lib/indieauth.js
Error messages in the user interface now include the stack trace, hidden under a `details` element. Clicking on the error name reveals the trace:
Prompted by #598.
> Better error reporting on frontend

- docs/configuration/index.md
- docs/configuration/time-zone.md
- helpers/config/index.js
- indiekit.config.js
- package-lock.json
- packages/endpoint-media/lib/file.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/tests/unit/file.js
- packages/endpoint-media/tests/unit/utils.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/endpoint-micropub/tests/unit/utils.js
- packages/indiekit/config/defaults.js
- packages/indiekit/locales/de.json
- packages/indiekit/locales/en.json
- packages/indiekit/locales/es.json
- packages/indiekit/locales/fr.json
- packages/indiekit/locales/id.json
- packages/indiekit/locales/nl.json
- packages/indiekit/locales/pl.json
- packages/indiekit/locales/pt.json
- packages/indiekit/locales/sr.json
- packages/indiekit/locales/zh-Hans-CN.json
- packages/indiekit/views/status.njk
In 1d69a37fac4ad5b3036981af111261f2ae82cbae I moved the `posts` and `media` content databases to the `application` settings object, away from `publication`.
In doing this, I missed updating `renderPath()` with should have been updated to take the `application` object. However, to correct this, I’d then need to provide both the `application` and `publication` objects to `renderPath()` as this needs `publication.timeZone`. Which got me thinking; maybe the `timeZone` setting belongs on the application object, too. This PR does that.
**This is a breaking change** but will ship in the next beta with a warning to update `publication.timeZone` to `application.timeZone`, if set.
(Having essentially 2 objects to store different settings may have been a bad idea… but something to think about at a …
> Replace `publication.timeZone` with `application.timeZone`

- docs/configuration/post-types.md
- docs/specifications.md
- helpers/media-data/index.js
- packages/endpoint-files/lib/controllers/files.js
- packages/endpoint-files/views/file.njk
- packages/endpoint-media/lib/controllers/query.js
- packages/endpoint-media/lib/media-content.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-media/lib/media-type-count.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/tests/unit/media-data.js
- packages/endpoint-media/tests/unit/media-type-count.js
- packages/endpoint-media/tests/unit/utils.js
Fixes #606.
Gets the post count by looking up the `post-type` property based on a media item’s `media-type` property.
Not sure if this’ll work though as it depends on a post being published _before_ the corresponding media item(s) is uploaded; the micropub media endpoint is asynchronous, and will publish media before a post has been sent to the server.
> Add post (media) count token to media endpoint

- package-lock.json
- packages/endpoint-auth/lib/pushed-authorization-request.js
- packages/endpoint-auth/lib/utils.js
- packages/endpoint-media/lib/file.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/tests/unit/file.js
- packages/endpoint-media/tests/unit/utils.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/package.json
- packages/endpoint-micropub/tests/unit/jf2.js
- packages/endpoint-micropub/tests/unit/utils.js
- packages/frontend/lib/filters/index.js
- packages/frontend/package.json
- packages/indiekit/lib/indieauth.js
- packages/indiekit/lib/utils.js
- packages/util/index.js
- packages/util/lib/string.js
- packages/util/package.json
- packages/util/tests/unit/string.js
Consolidates a number of string utility functions duplicated across different packages:
* `randomString`, used by:
* `endpoint-auth`
* `endpoint-media`
* `endpoint-micropub`
* `indiekit`
* `slugify`, used by:
* `endpoint-micropub`
* `frontend`
* `supplant`, used by:
* `endpoint-media`
* `endpoint-micropub`
This reduces the number of tests, down from 619 to 617.
> Consolidate string utility functions

- helpers/mock-agent/endpoint-syndicate.js
- helpers/mock-agent/syndicator-mastodon.js
- package-lock.json
- packages/endpoint-syndicate/tests/integration/200-syndicates-recent-post.js
- packages/endpoint-syndicate/tests/integration/200-syndicates-url-for-multiple-targets.js
- packages/endpoint-syndicate/tests/integration/200-syndicates-url-for-target.js
- packages/endpoint-syndicate/tests/integration/302-syndicates-url-with-redirect.js
- packages/endpoint-syndicate/tests/integration/403-syndicates-url-missing-update-scope.js
- packages/syndicator-mastodon/index.js
- packages/syndicator-mastodon/lib/mastodon.js
- packages/syndicator-mastodon/lib/utils.js
- packages/syndicator-mastodon/package.json
- packages/syndicator-mastodon/tests/index.js
- packages/syndicator-mastodon/tests/unit/mastodon.js
- packages/syndicator-mastodon/tests/unit/utils.js
Currently the Mastodon syndicator uses [Megladon](https://github.com/h3poteto/megalodon) to interface with the Mastodon API. This has a few problems:
* It doesn’t use the Fetch API but Axios, meaning testing against multiple syndicators means using both an Undici mock agent and Nock.
* This means it requires Axios in order to upload media, to get around the format of form data it will accept when posting that to the Mastodon API endpoint
* It’s not been possible to test uploading media as Nock doesn’t send `_httpMessage.path` value used by `form-data` module
In short: extra mis-matched dependencies that are hard to test against.
[Masto.js](https://github.com/neet/masto.js) uses the Fetch API. This means we can mock requests as we do elsewhere in the project, and it also has fewer …
> Mastodon syndicator: Use masto.js

- packages/endpoint-posts/index.js
- packages/endpoint-posts/lib/controllers/form.js
- packages/endpoint-posts/lib/controllers/new.js
- packages/endpoint-posts/lib/controllers/posts.js
- packages/endpoint-posts/locales/de.json
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/locales/es.json
- packages/endpoint-posts/locales/fr.json
- packages/endpoint-posts/locales/id.json
- packages/endpoint-posts/locales/nl.json
- packages/endpoint-posts/locales/pl.json
- packages/endpoint-posts/locales/pt.json
- packages/endpoint-posts/locales/sr.json
- packages/endpoint-posts/locales/zh-Hans-CN.json
- packages/endpoint-posts/tests/integration/200-get-new.js
- packages/endpoint-posts/views/new.njk
- packages/frontend/layouts/default.njk
Fixes #631.
When clicking ‘New post’, prior to showing a post screen that defaults to the Note post type, instead show a screen that asks the user which type of post they want to create:
If you select a post type from the dashboard, this selection screen is skipped.
> Ask user what type of post they want to create

- helpers/fixtures/jf2/note-visibility-unlisted.jf2
- packages/syndicator-mastodon/README.md
- packages/syndicator-mastodon/lib/utils.js
- packages/syndicator-mastodon/tests/unit/utils.js
Partial (or perhaps full) fix for #590.
If the `visibility` property has been set for a post, this same status is used when syndicating the post to Mastodon. As these properties have 1:1 relationship, no conversion is needed.
Now, is it the case that you might want a post to be public on your own website, but private or unlisted on Mastodon? Quite possibly. However, this takes us down the road of setting post visibility for each syndication target, which adds perhaps undue complexity.
> Mastodon syndicator: use same post visibility when syndicating status

- docs/get-started.md
- package-lock.json
- packages/create-indiekit/files/template.dockerfile
- packages/create-indiekit/files/template.dockerignore
- packages/create-indiekit/files/template.gitignore
- packages/create-indiekit/index.js
- packages/create-indiekit/lib/docker.js
- packages/create-indiekit/lib/files.js
- packages/create-indiekit/lib/package.js
- packages/create-indiekit/lib/setup-prompts.js
- packages/create-indiekit/lib/utils.js
- packages/create-indiekit/package.json
- packages/create-indiekit/tests/unit/docker.js
- packages/create-indiekit/tests/unit/files.js
- packages/create-indiekit/tests/unit/package.js
- packages/create-indiekit/tests/unit/utils.js
- packages/store-bitbucket/index.js
- packages/store-bitbucket/tests/index.js
- packages/store-ftp/index.js
- packages/store-ftp/tests/index.js
- packages/store-gitea/index.js
- packages/store-gitea/tests/index.js
- packages/store-github/index.js
- packages/store-github/tests/index.js
- packages/store-gitlab/index.js
- packages/store-gitlab/tests/index.js
- packages/syndicator-internet-archive/index.js
- packages/syndicator-internet-archive/tests/index.js
- packages/syndicator-mastodon/index.js
- packages/syndicator-mastodon/tests/index.js
This PR adds a question to the setup flow provided by the initialisation script. It asks a final question:
> Do you want to deploy your server using Docker?
If you select yes, `docker-compose.yml`, `Dockerfile` and `.dockerignore` files will be generated.
As the `docker-compose.yml` file needs to have any environment variables declared, and as some plugins require secrets to be provided via environment variables, a new `environment` getter has been added to plug-ins, and is used to provide the names of such variables to the function that generates the `docker-compose.yml` file.
There is also some light refactoring around the creation of files and package data, abstracting parts of the code into separate functions.
Closes #101.
> Add option to generate Docker files during setup

- packages/endpoint-micropub/lib/controllers/action.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/tests/integration/200-action-update-ignored.js
- packages/endpoint-syndicate/tests/integration/200-target-error.js
- packages/util/lib/date.js
If an update action is performed that results in no properties being updated, the Micropub endpoint continues as if there were, and indeed then makes only one change, adding/updated the `updated` property. This can result in unnecessary posts to a content store.
The above can be the result of a few cases:
* Syndication shenanigans such as those described in #638
* Submitting the post editing form without making any changes
This PR changes this such that:
1. Incoming post properties are saved
2. The update actions are performed
3. The updated properties are then compared with those saved earlier; if no changes are detected, the update action is cancelled, and the following is returned to the client:
```txt
HTTP/1.1 200 OK
Location: https://website.example/my-great-post
Content-type: …
```
> Prevent empty updates

- packages/endpoint-micropub/lib/post-type-count.js
When updating a post, the `renderPath` function is called as it is when creating a post. That in turn calls the `postTypeCount` function. This currently gets a value for all posts, that have the same `post-type`, posted on the same day. However, that will include the post being updated, incrementing the previous count by one, and thus changing the posts URL if it includes an `{n}` token.
This PR updates the MongoDB aggregation query such that it excludes from the aggregation match any posts that have the same URL as that being updated.
Fixes #621.
> Exclude current document from aggregated post count

- packages/endpoint-posts/lib/controllers/form.js
- packages/endpoint-posts/lib/middleware/post-data.js
- packages/endpoint-posts/locales/de.json
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/locales/es.json
- packages/endpoint-posts/locales/fr.json
- packages/endpoint-posts/locales/id.json
- packages/endpoint-posts/locales/nl.json
- packages/endpoint-posts/locales/pl.json
- packages/endpoint-posts/locales/pt.json
- packages/endpoint-posts/locales/sr.json
- packages/endpoint-posts/locales/zh-Hans-CN.json
- packages/endpoint-posts/views/post-form.njk
#635 opened a can of worms, reminding me of Indiekit’s current inability to submit any updates to a post that would effect its saved file location, certainly when interacting with certain Git providers. However, a good initial change to attempt to resolve the original issue is to:
* add hint text to explain that a post slug cannot be changed once a post has been saved
* prevent editing a slug for saved posts
> Only allow slug to be editable when creating a new post

- packages/endpoint-posts/index.js
- packages/endpoint-posts/lib/middleware/validation.js
- packages/endpoint-posts/locales/de.json
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/locales/es.json
- packages/endpoint-posts/locales/fr.json
- packages/endpoint-posts/locales/id.json
- packages/endpoint-posts/locales/nl.json
- packages/endpoint-posts/locales/pl.json
- packages/endpoint-posts/locales/pt.json
- packages/endpoint-posts/locales/sr.json
- packages/endpoint-posts/locales/zh-Hans-CN.json
- packages/endpoint-posts/views/post-form.njk
- packages/frontend/components/fieldset/styles.css
Partially address #538, #539 and #540.
Adds very basic and rudimentary support for creating and editing audio, photo and video posts.
To add a media post, you can first upload a file using the Files interface. That will give you a URL that you can then paste into the URL field for the given media post type. The photo post type form also asks for an accessible description, which is required:
You can now update a media post in so much as existing values can be edited (useful for updating alt text on a published photo):
With these additions, `audio`, `photo` and `video` post types are now marked as supported, and will show up on the dashboard and new post creation pages.
Subsequent updates will enable adding multiple media items, and adding/removing when updating.
> Basic media post type support

- packages/endpoint-posts/lib/controllers/form.js
- packages/endpoint-posts/locales/de.json
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/locales/es-419.json
- packages/endpoint-posts/locales/es.json
- packages/endpoint-posts/locales/fr.json
- packages/endpoint-posts/locales/id.json
- packages/endpoint-posts/locales/nl.json
- packages/endpoint-posts/locales/pl.json
- packages/endpoint-posts/locales/pt.json
- packages/endpoint-posts/locales/sr.json
- packages/endpoint-posts/locales/zh-Hans-CN.json
- packages/endpoint-posts/tests/integration/302-post-create.js
- packages/endpoint-posts/tests/integration/500-post-create.js
- packages/endpoint-posts/views/post-form.njk
Fixes #561.
When creating a new post, provides an advanced option that lets the user choose a specific publication date:
When editing an existing post, shows a date input to change the publication date:
`input[type="datetime-local"]` only accepts, and will only save, local date times, i.e. `2023-08-28T21:45`. However, we want to save dates with the local time zone; when reading an existing publication date we need to convert a zoned date to local time, and when saving we need to append the timezone designation. For example:
1. The time is 21:30, Europe/London, observing DST: `2023-08-28T21:30:00+01:00`
2. This is converted to local time: `2023-08-28T21:30` (removing the time zone and also any seconds)
3. User edits time to 20:15 local time: `2023-08-28T20:15`
4. Post is saved, the …
> Editable post publication date

- package-lock.json
- package.json
- packages/store-ftp/index.js
- packages/store-ftp/package.json
- packages/store-ftp/tests/index.js
Use `ssh2-sftp-client` to interface with SFTP servers. This then means we can use `@micham/sftp-mock-server` to mock an SFTP server in tests.
This does mean that non-secure FTP servers are no longer supported, but I think that’s probably a good thing.
Fixes #390.
> FTP store: Use `ssh2-sftp-client`

- packages/endpoint-media/lib/controllers/query.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/tests/integration/200-query-source.js
- packages/endpoint-micropub/lib/controllers/query.js
- packages/endpoint-micropub/lib/mf2.js
- packages/endpoint-micropub/tests/unit/mf2.js
- packages/endpoint-posts/lib/controllers/form.js
`properties.uid` returns the value for `_id`, which uses MongoDB’s `ObjectId()`.
> Add `uid` to post and media item queries

- helpers/mock-agent/endpoint-files.js
- packages/endpoint-files/index.js
- packages/endpoint-files/lib/controllers/files.js
- packages/endpoint-files/lib/middleware/file-data.js
- packages/endpoint-files/lib/utils.js
- packages/endpoint-files/tests/integration/200-file.js
- packages/endpoint-files/tests/integration/200-get-delete.js
- packages/endpoint-files/tests/integration/302-get-delete.js
- packages/endpoint-files/tests/integration/302-post-delete.js
- packages/endpoint-files/tests/integration/401-post-delete-unauthorized.js
- packages/endpoint-files/tests/integration/404-file.js
- packages/endpoint-files/tests/unit/utils.js
- packages/endpoint-micropub/lib/post-type-count.js
- packages/endpoint-posts/index.js
- packages/endpoint-posts/lib/controllers/post.js
- packages/endpoint-posts/lib/controllers/posts.js
- packages/endpoint-posts/lib/middleware/post-data.js
- packages/endpoint-posts/lib/utils.js
- packages/endpoint-posts/tests/integration/404-post.js
- packages/endpoint-posts/tests/unit/utils.js
Now that posts advertise their `uid`, we can use this to query posts and media items, and use UIDs in the frontend URL scheme. Removes quite a bit of complexity, and removes obscuration and lengthy slugs in the URL scheme.
> Query posts and media using `uid`

- packages/syndicator-mastodon/README.md
- packages/syndicator-mastodon/index.js
- packages/syndicator-mastodon/lib/mastodon.js
- packages/syndicator-mastodon/lib/utils.js
Defaults to `false`, but enables the option to include a permalink for shorter statues, not just those that go over the character limit.
I don’t like how the permalink looks inside brackets, so am updating the output from Brevity to instead show the permalink below the status text following 2 line breaks.
Fixes #568.
> Add option to include permalink in Mastodon status

- packages/endpoint-syndicate/lib/utils.js
- packages/endpoint-syndicate/tests/unit/utils.js
Fixes an issue where the syndication endpoint was looping over all configured syndication targets and comparing their URLs to that provided in a `mp-syndicate-to` property, but without accounting for the fact that this value could be an array.
This lead to all syndication targets being syndicated against, even if not selected by the author when creating a post.
Now we loop through each value in `mp-syndicate-to`, check that a target for that value has been configured, and that the post has not already been syndicated to that URL.
Hopefully this makes syndication a little less buggier, but this part of the application remains more challenging than it perhaps should be.
> Correctly syndicate to configured targets

- indiekit.config.js
- packages/endpoint-micropub/lib/controllers/action.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/tests/unit/jf2.js
If a post was created using form-encoded data, if the `publication.enrichPosts` option was enabled, post data wasn’t being enriched.
We can enrich JF2 using `fetchReferences` exported from `mf2tojf2`, though not from the main export of that module. Maybe it should be a top-level export? Will consider that as a feature to be added to `mf2tojf2`
Fixes #671.
> Fetch references for form-encoded requests

- helpers/fixtures/jf2/post-template-properties.jf2
- packages/endpoint-micropub/lib/post-content.js
- packages/preset-hugo/index.js
- packages/preset-hugo/test/index.js
- packages/preset-jekyll/index.js
- packages/preset-jekyll/test/index.js
Currently, the provided preset plugins dictate the post properties that will be output in a post’s front matter. And yet, we allow users to add different post types that, down the line, could output different properties.
This PR updates the 2 preset plugins, adjusting only the properties that need adjusting, and thus allowing unknown properties to be output. This also means these presets don’t need updating every time there is a change to the posts and properties produced by the/a Micropub plugin.
Also, this PR prevents `mp-*` properties from being sent to the `postTemplate()` function; these are only intended for sending commands to Micropub servers, and should not be used in posts.
> Update Jekyll and Hugo post templates to accept unknown properties 

- packages/endpoint-posts/index.js
- packages/endpoint-posts/lib/controllers/form.js
- packages/endpoint-posts/lib/middleware/post-data.js
- packages/endpoint-posts/lib/middleware/validation.js
- packages/endpoint-posts/lib/utils.js
- packages/endpoint-posts/locales/de.json
- packages/endpoint-posts/locales/en.json
- packages/endpoint-posts/locales/es-419.json
- packages/endpoint-posts/locales/es.json
- packages/endpoint-posts/locales/fr.json
- packages/endpoint-posts/locales/id.json
- packages/endpoint-posts/locales/nl.json
- packages/endpoint-posts/locales/pl.json
- packages/endpoint-posts/locales/pt.json
- packages/endpoint-posts/locales/sr.json
- packages/endpoint-posts/locales/zh-Hans-CN.json
- packages/endpoint-posts/test/unit/utils.js
- packages/endpoint-posts/views/post-form.njk
- packages/frontend/components/error-message/styles.css
- packages/frontend/components/event-duration/index.js
- packages/frontend/components/event-duration/styles.css
- packages/frontend/scripts/app.js
- packages/frontend/styles/app.css
- Add (optional) location fields with localised strings
- Add start and (optional) end datetime fields with localised strings
- Show location and start/end datetime fields for event post type
- Add validation for name and start date for event post type
- Add event post type to list of supported post types
- Add `<event-duration>` element that allows toggling between `input[type=datetime-local]` and `input[date]` depending on whether times are needed for the event 
- Update deriving location property so location can contain a venue (`h-card`) or address (`h-adr`) and/or geographic coordinates (`h-geo`)
In future iterations we can use geolocation to find an address and geographic coordinates from a fuzzy free-text search, but this simpler implementation means Indiekit can support creating …
> Event post type

- helpers/config/index.js
- indiekit.config.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/test/unit/media-data.js
- packages/endpoint-media/test/unit/utils.js
- packages/endpoint-micropub/lib/config.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/post-type-discovery.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/test/unit/post-data.js
- packages/endpoint-micropub/test/unit/post-type-discovery.js
- packages/endpoint-micropub/test/unit/utils.js
- packages/endpoint-posts/includes/endpoint-posts-widget.njk
- packages/endpoint-posts/lib/controllers/new.js
- packages/endpoint-posts/lib/middleware/post-data.js
- packages/endpoint-posts/lib/middleware/validation.js
- packages/endpoint-posts/lib/utils.js
- packages/endpoint-posts/test/unit/utils.js
- packages/indiekit/config/defaults.js
- packages/indiekit/lib/post-types.js
- packages/indiekit/test/unit/post-types.js
- packages/indiekit/views/status.njk
- packages/preset-hugo/lib/post-types.js
- packages/preset-hugo/test/index.js
- packages/preset-hugo/test/unit/post-types.js
- packages/preset-jekyll/lib/post-types.js
- packages/preset-jekyll/test/index.js
- packages/preset-jekyll/test/unit/post-types.js
I was right the first time…
Previously, post type configuration was stored using keyed values for each post type, i.e.:
```js
{
article: {
name: "Article"
}
}
```
I later changed this to use an array of objects with a `type` property, i.e.:
```js
[
{
type: "article",
name: "Article"
}
}
```
This was to align with the expected format when querying a Micropub endpoint. And yet, when it comes to managing, transforming and merging post types, it's easier to merge based on a key. And when you think about it, there shouldn’t be multiple objects with the same `type` value, and with the former format we can infer this.
As part of a broader change as to how post types are configured and customised, this PR reverts back to former model. Meanwhile, the model expected to be provided in by a Micropub …
> Store post type config in object

- docs/configuration/index.md
- helpers/database/index.js
- packages/frontend/layouts/default.njk
- packages/indiekit/index.js
- packages/indiekit/lib/middleware/locals.js
- packages/indiekit/lib/mongodb.js
- packages/indiekit/test/unit/mongodb.js
Fixes #690.
- `getMongodbClient` now provides either a `client` or `error` value. If `error` is provided (which contains an `Error` object), this is then passed on to application locals so that an error message can be displayed in the user interface (in addition to one being shown in the console)
- Errors are provided when **creating** a new MongoDB client, and when **connecting** to one that has been successfully created:
I have tested this with the following connection strings:
- `https://localhost:27017` (not a MongoDB address)
- `mongodb+srv://localhost:27017` (`mongodb+srv` protocol with a disallowed port)
- `mongodb://foo:bar@localhost` (invalid credentials)
I can’t seem to produce an error however if the database URL can’t be resolved, for example `mongodb://mongo.example:12345`. …
> Immediately notify the user about connection issues with MongoDB

- packages/endpoint-micropub/lib/post-content.js
- packages/endpoint-micropub/lib/post-data.js
I think that adding even a single log statement for each CRUD operation would aid troubleshooting and improve debuggability.
> Log CRUD operations on post-data and post-content in micropub endpoint

- packages/endpoint-micropub/lib/controllers/query.js
This PR addresses #692 .
A more robust solution would be to run a validator (ajv, zod, joi, JSON schema, etc...) against each document extracted from the MongoDB `posts` collection. But that would mean introducing a new dependency in the codebase.
> Ignore MongoDB documents in `posts` collection that have no `properties` field

- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/test/unit/utils.js
- packages/util/index.js
- packages/util/lib/date.js
- packages/util/test/unit/date.js
Form-encoded query strings are passed to the `decodeQueryParameter` method, where the URL is decoded and `+`s get replaced with spaces. However, given the following query:
```
h=entry&content=Testing+indiepass&post-status=published&category%5B%5D=Indiepass%2C+testing&published=2024-02-14T13%3A24%3A00%2B0100&post-status=published`
```
While `Testing+indiepass` is correctly converted to `Testing indiepass`, `2024-02-14T13%3A24%3A00%2B0100` is converted to `2024-02-14T13:24:00 0100` – the `+` gets replaced with a space. However, in date strings, `+` is used for time zone offsets, and so removing it causes parsing and conversion issues further along the pipeline.
This PR adds a new `isDate` utility method, that checks if a value can be converted to a `Date` and successful be parsed …
> Don’t decode date parameter values in Micropub form-encoded query strings

- helpers/frontend/views/frontend-form.njk
- packages/endpoint-posts/includes/post-fields/content.njk
- packages/frontend/components/character-count/index.js
- packages/frontend/components/character-count/macro.njk
- packages/frontend/components/character-count/styles.css
- packages/frontend/components/character-count/template.njk
- packages/frontend/layouts/default.njk
- packages/frontend/locales/de.json
- packages/frontend/locales/en.json
- packages/frontend/locales/es-419.json
- packages/frontend/locales/es.json
- packages/frontend/locales/fr.json
- packages/frontend/locales/id.json
- packages/frontend/locales/nl.json
- packages/frontend/locales/pl.json
- packages/frontend/locales/pt.json
- packages/frontend/locales/sr.json
- packages/frontend/locales/zh-Hans-CN.json
- packages/frontend/scripts/app.js
- packages/frontend/styles/app.css
Based on the [Character count component from the GOV.UK Design System](https://design-system.service.gov.uk/components/character-count/#options-character-count-example--count-message).
The `<character-count>` component provides a visible, real-time character and word count for a `<textarea>` as well as a visually hidden counter that announces updates to screen readers periodically. [Some more background surrounding this approach can be found in this blog post by David Cox](https://dav-idc.com/making-a-character-count-component-more-accessible/).
Unlike the GOV.UK example, this component provides only a character and word count, and doesn’t inform or enforce any limits. Different social networks will have different limits, so a character count only needs to be informative. This component …
> Character count component, show character and word count for content field

- docs/.vitepress/config.js
- docs/.vitepress/theme/custom.css
- docs/plugins/api/.plugin-constructor.md
- docs/plugins/api/add-endpoint.md
- docs/plugins/api/add-preset.md
- docs/plugins/api/add-store.md
- docs/plugins/api/add-syndicator.md
- docs/plugins/api/error.md
- package-lock.json
- package.json
Updates the plug-in API docs to follow a structure similar to that used on MDN. Roughly speaking, that means showing the syntax, briefly outlining the different properties and methods, then expanding below with examples, finishing off with links to related content.
In part, this should help address #652. Further changes will be needed in other parts of the documentation, but this is a good start.
Plan is to:
> Update plug-in API docs to follow MDN format

- docs/.vitepress/config.js
- docs/concepts.md
- docs/configuration/.option-contains-secrets.md
- docs/configuration/.plugin-secrets.md
- docs/configuration/application.md
- docs/configuration/commit-messages.md
- docs/configuration/index.md
- docs/configuration/post-template.md
- docs/configuration/post-types.md
- docs/configuration/publication.md
- docs/configuration/tokens.md
- docs/plugins/api/add-post-type.md
- docs/plugins/post-types.md
- packages/endpoint-media/lib/media-type-count.js
- packages/endpoint-micropub/lib/post-type-count.js
- packages/indiekit/index.js
- Break configuration into separate pages for `application` and `publication`
- Update links in application to these new pages
- Update documentation around post type configuration
- Remove references to upcoming new post type plug-in feature
- Fix typos
> Update documentation for configuration, including post types

- docs/plugins/api/add-syndicator.md
- packages/endpoint-posts/lib/utils.js
- packages/endpoint-posts/test/unit/utils.js
- packages/syndicator-internet-archive/index.js
- packages/syndicator-internet-archive/test/index.js
- packages/syndicator-mastodon/index.js
- packages/syndicator-mastodon/test/index.js
Instead of throwing 500 error, show syndicator target errors in the posting interface:
Fixes #710
> Show syndication target errors

- docs/configuration/tokens.md
- helpers/fixtures/jf2/article-content-provided.jf2
- helpers/fixtures/jf2/article-slug-provided-empty.jf2
- helpers/fixtures/jf2/note-slug-missing-no-name.jf2
- helpers/fixtures/jf2/note-slug-provided-unslugified.jf2
- helpers/fixtures/jf2/note-slug-provided.jf2
- packages/endpoint-media/lib/file.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/test/unit/file.js
- packages/endpoint-media/test/unit/utils.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/test/unit/jf2.js
- packages/endpoint-micropub/test/unit/utils.js
Fixes #717 
Previously, an `mp-slug` property would be created for a post, even if a user hadn’t chosen a slug (using slugified `name` if no `mp-slug`, else generating a random 5 character string if no `name`). This `mp-slug` value was then used for the `{slug}` path token.
In a recent beta however, `mp-*` values were not provided to the post template function. Even if a slug was defined, this value was no longer accessible to post templates. 
In what might be a subtle change, this PR makes it so that if a value for `mp-slug` is provided, a `slug` value is saved to post properties (and thus available to front matter and downstream static site generators).
However, if no `mp-slug` is provided, no `slug` value is saved to the post template. However, as path may contain a `{slug}` token, …
> Decouple slug property from slug path tokens; add `random` path token

- packages/endpoint-auth/lib/controllers/metadata.js
- packages/endpoint-auth/lib/scope.js
- packages/endpoint-auth/test/unit/scope.js
- packages/indiekit/locales/de.json
- packages/indiekit/locales/en.json
- packages/indiekit/locales/es-419.json
- packages/indiekit/locales/es.json
- packages/indiekit/locales/fr.json
- packages/indiekit/locales/id.json
- packages/indiekit/locales/nl.json
- packages/indiekit/locales/pl.json
- packages/indiekit/locales/pt.json
- packages/indiekit/locales/sr.json
- packages/indiekit/locales/sv.json
- packages/indiekit/locales/zh-Hans-CN.json
Fixes #715.
Previously, the consent screen (and therefore the tokens generated) only allowed users to check 5 pre-defined scopes: `create`, `update`, `draft`, `delete` and `media`. Other scopes that were requested couldn’t be seen or (un)checked, and there was no way of showing which scopes were unsupported by Indiekit.
This PR:
- Changes the consent screen so that only requested scopes are shown
- Localisations have been added for [all known scopes](https://indieweb.org/scope); if a scope is requested that is not known, then the scope name is shown instead of a localised string
- `profile` and `email` are not supported by the IndieAuth endpoint, so these are shown, but disabled and marked as unsupported.
> Only show requested scopes, indicate which are not supported

- docs/plugins/api/add-endpoint.md
- packages/endpoint-files/index.js
- packages/endpoint-posts/index.js
- packages/indiekit/lib/controllers/manifest.js
- packages/indiekit/lib/middleware/locals.js
- packages/indiekit/lib/shortcuts.js
- packages/indiekit/test/unit/navigation.js
- packages/indiekit/test/unit/shortcuts.js
Adds support for endpoints to supply [`shortcuts`](https://developer.mozilla.org/en-US/docs/Web/Manifest/shortcuts) to the web app manifest:
> Web app manifest shortcuts

- helpers/frontend/views/frontend-components.njk
- helpers/frontend/views/frontend-form.njk
- packages/endpoint-files/locales/nl.json
- packages/endpoint-files/locales/pt.json
- packages/frontend/components/file-input/index.js
- packages/frontend/components/file-input/macro.njk
- packages/frontend/components/file-input/styles.css
- packages/frontend/components/file-input/template.njk
- packages/frontend/components/input/styles.css
- packages/frontend/components/progress/macro.njk
- packages/frontend/components/progress/styles.css
- packages/frontend/components/progress/template.njk
- packages/frontend/layouts/default.njk
- packages/frontend/locales/de.json
- packages/frontend/locales/en.json
- packages/frontend/locales/es-419.json
- packages/frontend/locales/es.json
- packages/frontend/locales/fr.json
- packages/frontend/locales/id.json
- packages/frontend/locales/nl.json
- packages/frontend/locales/pl.json
- packages/frontend/locales/pt.json
- packages/frontend/locales/sr.json
- packages/frontend/locales/sv.json
- packages/frontend/locales/zh-Hans-CN.json
- packages/frontend/scripts/app.js
- packages/frontend/styles/app.css
- packages/post-type-audio/includes/post-types/audio-field.njk
- packages/post-type-photo/includes/post-types/photo-field.njk
- packages/post-type-video/includes/post-types/video-field.njk
Partially fixes #538, #539 and #540.
Adds a `fileInput` component, that progressively enhances an `<input type="text">` to be populated from the upload from an injected `<input type="file">`. After clicking the file selector and choosing a file, a fetch request is initiated that uploads the chosen file and returns the URL from the media endpoint.
Possibly a number of ways this could be improved, but I think this is a good first pass at making uploading images inline easier, certainly easier than going to the separate file upload page and copy and pasting an uploaded file URL.
Given restrictions around initiating a file picker programmatically, and without universal support for `window.showOpenFilePicker()`, am using a `<label>` styled as a `<button>` which is used to trigger the hidden …
> Media file upload component

- packages/frontend/lib/filters/url.js
- packages/frontend/test/unit/filters/url.js
- packages/indiekit/locales/de.json
- packages/indiekit/locales/en.json
- packages/indiekit/locales/es-419.json
- packages/indiekit/locales/es.json
- packages/indiekit/locales/fr.json
- packages/indiekit/locales/id.json
- packages/indiekit/locales/nl.json
- packages/indiekit/locales/pl.json
- packages/indiekit/locales/pt.json
- packages/indiekit/locales/sr.json
- packages/indiekit/locales/zh-Hans-CN.json
- Remove trailing slash from domains without a path component
- Remove mention of IndieAuth (implementation detail doesn’t need to be exposed to user)
| Before | After |
| - | - |
| ![Login screen before.](https://github.com/getindiekit/indiekit/assets/813383/e0eaa0c0-5d95-408b-a884-094937410dee) | ![Login screen after.](https://github.com/getindiekit/indiekit/assets/813383/cb4ae1b9-3b7e-4310-bfc7-be33bd2db1fe) |
> Simplify login screen

- docs/configuration/tokens.md
- helpers/fixtures/jf2/article-content-provided.jf2
- helpers/fixtures/jf2/article-slug-provided-empty.jf2
- helpers/fixtures/jf2/note-slug-missing-no-name.jf2
- helpers/fixtures/jf2/note-slug-provided-unslugified.jf2
- helpers/fixtures/jf2/note-slug-provided.jf2
- packages/endpoint-media/lib/file.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/test/unit/file.js
- packages/endpoint-media/test/unit/utils.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/test/unit/jf2.js
- packages/endpoint-micropub/test/unit/post-data.js
- packages/endpoint-micropub/test/unit/utils.js
- packages/endpoint-posts/views/post-form.njk
- packages/preset-eleventy/lib/post-template.js
- packages/preset-hugo/lib/post-template.js
- packages/preset-jekyll/lib/post-template.js
Argh. Slugs are a pain. They’re an essential component of the Micropub endpoint and need to be stable and predictable as they can affect generated paths (if a path don’t exist in a content store, things quickly fall apart).
This PR:
Need more use cases for it makes sense to supply `slug` property to front matter properties for different static site generators, however if using `postTemplate`, the `slug` property will be provided.
/cc @aciccarello
> Refactor slugs

- packages/frontend/components/file-input/index.js
- packages/frontend/components/file-input/template.njk
- packages/frontend/components/geo-input/index.js
- packages/frontend/components/geo-input/template.njk
Fixes #729.
Once we’ve instantiated new elements in the geo input and file input components (the find button for the geo input, the file picker ‘button’ for the file input), we don’t need to create them again when cloning (for example within the add another component).
Thanks to @tvararu for helping me debug this issue. :shipit:
> Fix add another re-cloning elements in geo and file inputs 

- indiekit.config.js
- package-lock.json
- packages/endpoint-media/README.md
- packages/endpoint-media/index.js
- packages/endpoint-media/lib/controllers/action.js
- packages/endpoint-media/lib/media-transform.js
- packages/endpoint-media/package.json
> Image transformations

- packages/endpoint-micropub/lib/post-type-discovery.js
- packages/endpoint-micropub/test/unit/post-type-discovery.js
Fixes #756.
Rather than check for the presence of the `name` property, check for the presence of a value assigned to `name`.
> Ignore empty name property in post type discovery

- packages/store-github/index.js
This PR tries to improve the error messages a user can encounter when performing CRUD operations on the GitHub content store. It also adds a few debug logs useful when troubleshooting such operations.
The debug logs of this PR can be selectively enabled by setting the DEBUG environment variable:
```txt
DEBUG="indiekit-store:github"
```
> More detailed error messages for GitHub store CRUD operations

- .github/workflows/build.yml
- helpers/mock-agent/endpoint-auth.js
- packages/endpoint-auth/lib/client.js
- packages/endpoint-auth/test/unit/client.js
- packages/indiekit/lib/controllers/client.js
- packages/indiekit/lib/indieauth.js
- packages/indiekit/lib/routes.js
- packages/indiekit/test/integration/200-client.js
This PR:
- Provides a client metadata endpoint at `/id` that serves a JSON file containing client metadata
- Uses that endpoint for the server’s `client_id`
- Updates the authentication endpoint to look for a JSON response from `client_id`, and if found, validate and then use client metadata found in that file
Fixes #754.
> Client metadata

- helpers/fixtures/jf2/note-slug-missing-no-name.jf2
- helpers/mock-agent/store-gitea.js
- helpers/mock-agent/store-github.js
- helpers/mock-agent/store-gitlab.js
- indiekit.config.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-micropub/lib/jf2.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/test/unit/jf2.js
- packages/store-bitbucket/index.js
- packages/store-bitbucket/test/index.js
- packages/store-file-system/index.js
- packages/store-file-system/test/index.js
- packages/store-ftp/index.js
- packages/store-ftp/test/index.js
- packages/store-gitea/index.js
- packages/store-gitea/test/index.js
- packages/store-github/index.js
- packages/store-github/test/index.js
- packages/store-gitlab/index.js
- packages/store-gitlab/test/index.js
- packages/store-s3/index.js
- packages/store-s3/test/index.js
- packages/util/index.js
- packages/util/lib/string.js
- packages/util/test/unit/string.js
> Prevent duplicates being created with the same URL

- package-lock.json
- packages/indiekit/lib/middleware/locals.js
- packages/indiekit/package.json
- packages/util/index.js
- packages/util/lib/string.js
- packages/util/test/unit/string.js
Using SHA1 algorithm, and using `node:crypto` `createHash()` method is faster than using `hasha` with the md5 algorithm. SHA1 is also faster than SHA256 or md5 algorithms.
Running on Railway server:
| Asset (hasher) | Time |
| - | - |
| JS (`hasha`, md5) | 2.136s |
| JS (`hasha`, sha256) | 1.601s |
| JS (`hasha`, sha1) | 1.464s |
| JS (`createHash("sha1")`) | 1.324s |
| Asset (hasher) | Time |
| - | - |
| CSS (`hasha`, md5) | 0.602ms |
| CSS (`hasha`, sha256) | 0.375ms |
| CSS (`hasha`, sha1) | 0.224ms |
| CSS (`createHash("sha1")`) | 0.122ms |
> Use SHA1 algorithm for generating asset hashes

- docs/.vitepress/config.js
- docs/api/add-collection.md
- docs/api/index.md
- packages/endpoint-json-feed/lib/controllers/json-feed.js
- packages/endpoint-media/index.js
- packages/endpoint-media/lib/controllers/query.js
- packages/endpoint-media/lib/media-data.js
- packages/endpoint-media/lib/media-type-count.js
- packages/endpoint-media/lib/utils.js
- packages/endpoint-media/test/unit/media-data.js
- packages/endpoint-media/test/unit/media-type-count.js
- packages/endpoint-micropub/index.js
- packages/endpoint-micropub/lib/controllers/query.js
- packages/endpoint-micropub/lib/post-data.js
- packages/endpoint-micropub/lib/post-type-count.js
- packages/endpoint-micropub/lib/utils.js
- packages/endpoint-micropub/test/unit/post-data.js
- packages/endpoint-micropub/test/unit/post-type-count.js
- packages/endpoint-syndicate/lib/controllers/syndicate.js
- packages/endpoint-syndicate/lib/utils.js
- packages/endpoint-syndicate/test/unit/utils.js
- packages/indiekit/index.js
- packages/indiekit/lib/controllers/feed.js
- packages/indiekit/lib/middleware/locals.js
- packages/indiekit/test/index.js
- packages/indiekit/test/server.js
- Adds a new `addCollection` API method. Fails if adding a collection with a name that already exists.
- `endpoint-micropub` plug-in takes responsibility for adding the `posts` collection
- `endpoint-media` plug-in takes responsibility for adding the `media` collection
- `Indiekit` instance tidied up a bit, moving setup out of `bootstrap()` and adding the properties `cache`, `database` and the following methods: `connectMongodbClient()` and `closeMongodbClient()`
- Collections added to `Indiekit.collections` `Map` (exposed via Express locals as `application.collections`).
> Provide `addCollection` API method, add to application.collections `Map`
