app/middleware/micropub/query.js
lib/publication/get-posts.js
lib/publication/index.js
test/app/middleware/micropub/query.test.js

Add support for querying post list

---

docs/deploy.md

Add TZ config var

---

packages/endpoint-media/locales/de.js
packages/endpoint-micropub/locales/de.js
packages/endpoint-share/locales/de.js
packages/indiekit/locales/de.js

I changed some strings so these are gramatically correct. If you have questions, please write me back.

fixes #286 - german translations  

---

packages/store-bitbucket/README.md
packages/store-bitbucket/index.js
packages/store-ftp/README.md
packages/store-ftp/index.js
packages/store-gitea/README.md
packages/store-gitea/index.js
packages/store-github/README.md
packages/store-github/index.js
packages/store-gitlab/README.md
packages/store-gitlab/index.js
packages/syndicator-internet-archive/README.md
packages/syndicator-internet-archive/index.js
packages/syndicator-twitter/README.md
packages/syndicator-twitter/index.js

Add environment variables as defaults for secret values

---

packages/endpoint-media/lib/file.js
packages/endpoint-media/lib/media-data.js
packages/endpoint-media/tests/unit/file.js
packages/endpoint-media/tests/unit/media-data.js
packages/endpoint-micropub/lib/post-data.js
packages/endpoint-micropub/tests/unit/post-data.js

Provide useful error message if a post type not configured

---

docs/options.md
packages/indiekit/config/defaults.js
packages/indiekit/index.js
packages/indiekit/lib/cache.js
packages/indiekit/lib/publication.js
packages/indiekit/tests/unit/cache.js
packages/indiekit/tests/unit/publication.js

* Use keyv to manage application caching saving
* Ensure categories can still be fetched if no database has been configured
* Update unit tests
This refactors possibly the oldest piece of code in this project; what goes around, comes around.

Use keyv for categories cache

---

localazy.json
packages/endpoint-files/views/upload.njk
packages/endpoint-share/views/share.njk
packages/frontend/components/error-message/template.njk
packages/frontend/components/error-summary/template.njk
packages/frontend/components/input/template.njk
packages/frontend/components/label/template.njk
packages/frontend/components/select/template.njk
packages/frontend/components/summary/template.njk
packages/frontend/components/textarea/template.njk
packages/frontend/layouts/form.njk
packages/frontend/locales/de.json
packages/frontend/locales/en.json
packages/frontend/locales/es.json
packages/frontend/locales/fr.json
packages/frontend/locales/id.json
packages/frontend/locales/nl.json
packages/frontend/locales/pt.json
packages/frontend/package.json
packages/indiekit/lib/application.js
packages/indiekit/locales/de.json
packages/indiekit/locales/en.json
packages/indiekit/locales/es.json
packages/indiekit/locales/fr.json
packages/indiekit/locales/id.json
packages/indiekit/locales/nl.json
packages/indiekit/locales/pt.json
packages/indiekit/views/status.njk

Move localisations that are (or can be) used as default values in components into the frontend package, maintaining the separation of concerns.

Frontend localisations

---

indiekit.config.cjs
package-lock.json
packages/endpoint-posts/lib/controllers/create.js
packages/endpoint-posts/locales/en.json
packages/endpoint-posts/views/post-create.njk
packages/frontend/components/field/styles.css
packages/frontend/components/token-input/index.js
packages/frontend/components/token-input/styles.css
packages/frontend/lib/rollup.js
packages/frontend/package.json
packages/frontend/scripts/app.js

Lovely stuff[^1].
[^1]: Am using the [`tokenfield`](https://github.com/KaneCohen/tokenfield) library for this. Keyboard control seems pretty good, but will need to review the accessibility of the delete tag link; I suspect it’ll get announced as ‘×’, which isn’t very helpful. Might also need to look at the suggestions list, as that doesn’t seem have any accessibility considerations given to it at all. Needs an in-depth review and suggested changes being made upstream.

Token input component and categories field

---

packages/frontend/components/pagination/styles.css

fix: pagination wraps if list width exceed container width

---

packages/endpoint-media/lib/media-data.js
packages/endpoint-micropub/lib/post-data.js

Only add data to configured database

---

docs/accessibility.md
packages/endpoint-posts/views/post-form.njk
packages/frontend/components/token-input/index.js
packages/frontend/components/token-input/template.njk
packages/frontend/lib/utils/focusable-elements.js

Fixes #578.
There might still be some edge cases, as to be expected when trying to create a complex interaction, but the main issue around focus getting trapped is fixed.

Prevent focus getting trapped inside token input

---

docs/concepts.md
packages/endpoint-micropub/lib/jf2.js
packages/endpoint-micropub/tests/unit/jf2.js
packages/syndicator-internet-archive/README.md
packages/syndicator-internet-archive/index.js
packages/syndicator-mastodon/README.md
packages/syndicator-mastodon/index.js

Remove `forced` syndication option

---

docs/plugins/api/add-store.md
helpers/mock-agent/store-gitea.js
helpers/mock-agent/store-github.js
helpers/mock-agent/store-gitlab.js
packages/endpoint-micropub/lib/post-content.js
packages/endpoint-micropub/lib/post-data.js
packages/store-bitbucket/index.js
packages/store-bitbucket/tests/index.js
packages/store-file-system/index.js
packages/store-file-system/tests/index.js
packages/store-ftp/index.js
packages/store-gitea/index.js
packages/store-gitea/tests/index.js
packages/store-github/index.js
packages/store-github/tests/index.js
packages/store-gitlab/index.js
packages/store-gitlab/tests/index.js

Add ability to rename file when updating a post

---

docs/configuration/localisation.md
packages/endpoint-auth/locales/es-419.json
packages/endpoint-files/locales/es-419.json
packages/endpoint-posts/locales/es-419.json
packages/endpoint-share/locales/es-419.json
packages/error/locales/es-419.json
packages/frontend/locales/es-419.json
packages/indiekit/config/defaults.js
packages/indiekit/locales/es-419.json

Localisation contributed by [Claudia Botero](https://localazy.com/p/indiekit/contributors/tradbo). Closes #653.

Latin American Spanish localisation

---

helpers/frontend/views/frontend-form.njk
packages/frontend/components/checkboxes/index.js
packages/frontend/components/checkboxes/styles.css
packages/frontend/components/checkboxes/template.njk
packages/frontend/components/radios/index.js
packages/frontend/components/radios/styles.css
packages/frontend/components/radios/template.njk
packages/frontend/layouts/default.njk
packages/frontend/scripts/app.js

This PR add the ability to:
* show conditional content when selecting a radio button
* show conditional content when selecting a checkbox
* provide a checkbox that unchecks other checkboxes in same group (exclusive behaviour)

Conditional checkboxes and radios

---

docs/plugins/api/add-store.md
helpers/mock-agent/store-gitea.js
helpers/mock-agent/store-github.js
helpers/mock-agent/store-gitlab.js
packages/store-bitbucket/index.js
packages/store-bitbucket/tests/index.js
packages/store-file-system/index.js
packages/store-file-system/tests/index.js
packages/store-ftp/index.js
packages/store-ftp/tests/index.js
packages/store-gitea/index.js
packages/store-gitea/tests/index.js
packages/store-github/index.js
packages/store-github/tests/index.js
packages/store-gitlab/index.js
packages/store-gitlab/tests/index.js

Update store-plugins to return file location when creating/updating

---

packages/endpoint-files/lib/endpoint.js
packages/endpoint-posts/lib/endpoint.js

Accept Micropub responses with `204 No Content`

---

packages/create-indiekit/bin/create.js

Update minimum supported node version advertised by create module

---

packages/indiekit/lib/controllers/feed.js

Check for database before querying for posts to show in JF2 feed

---

packages/indiekit/config/express.js
packages/indiekit/index.js
packages/indiekit/lib/mongodb.js

Recreating #750 to get around some unfathomable GitHub workflow weirdness preventing me from merging that PR.

Add debug logs to troubleshoot the creation of the Indiekit/Express server and the connection to MongoDB

---

docs/development.md

Recreating #749 to get around some unfathomable GitHub workflow weirdness preventing me from merging that PR.
Also includes a few tweaks to the content suggested by @jackdbd.

docs: improve documentation on how to setup a dev environment

---

docs/concepts.md

Hey @paulrobertlloyd just noticed a stray link to the Hugo preset plugin.
Just noticed the Eleventy preset has landed too 🙌

Update link to Hugo preset concepts.md

---

docs/api/add-endpoint.md
package-lock.json
package.json
packages/endpoint-auth/package.json
packages/endpoint-files/index.js
packages/endpoint-files/package.json
packages/endpoint-image/package.json
packages/endpoint-json-feed/package.json
packages/endpoint-media/lib/controllers/action.js
packages/endpoint-media/package.json
packages/endpoint-micropub/lib/controllers/action.js
packages/endpoint-micropub/package.json
packages/endpoint-micropub/test/unit/config.js
packages/endpoint-posts/index.js
packages/endpoint-posts/lib/middleware/post-data.js
packages/endpoint-posts/package.json
packages/endpoint-share/index.js
packages/endpoint-share/lib/controllers/share.js
packages/endpoint-share/package.json
packages/endpoint-syndicate/lib/token.js
packages/endpoint-syndicate/package.json
packages/indiekit/package.json

Breaking changes that impact Indiekit and fixed in this PR are:
- [Path route matching syntax](https://expressjs.com/en/guide/migrating-5#path-syntax)
- [`request.body` returns `undefined` when the body has not been parsed](https://expressjs.com/en/guide/migrating-5#req.body)

Upgrade to Express 5

---

packages/post-type-video/README.md

Update reference to post type in README.md

---

docs/configuration/localisation.md
packages/endpoint-auth/locales/it.json
packages/endpoint-files/locales/it.json
packages/endpoint-posts/locales/it.json
packages/endpoint-share/locales/it.json
packages/endpoint-webmention-io/locales/it.json
packages/error/locales/it.json
packages/frontend/locales/it.json
packages/indiekit/config/locales.js
packages/indiekit/locales/it.json
packages/post-type-audio/locales/it.json
packages/post-type-bookmark/locales/it.json
packages/post-type-event/locales/it.json
packages/post-type-jam/locales/it.json
packages/post-type-like/locales/it.json
packages/post-type-photo/locales/it.json
packages/post-type-reply/locales/it.json
packages/post-type-repost/locales/it.json
packages/post-type-rsvp/locales/it.json
packages/post-type-video/locales/it.json

Adds Italian localisation, started by @jackdbd.

Italian localisation
